### ISSUE TITLE
项目只能windows下运行

### ISSUE THREAD

**Issue by wangjiaxi90** [enpeizhao/CVprojects#1]
您好，我fork了代码之后本地运行报错。
![image](https://user-images.githubusercontent.com/37741159/143162047-66cf0e15-a79c-431f-a28e-ed65f5e38e36.png)
google搜到的结果是 comtypes 这个包只能在windows运行，由于我对这个包的功能不太了解，想请问一下，有没有mac或者linux系统下的替代包。

**Comment by enpeizhao** [comment]
osax

**Comment by enpeizhao** [comment]
[查看最新社区贡献代码](https://github.com/enpeizhao/CVprojects/blob/main/codes/6.hand_control_volume_mac.py)
