### ISSUE TITLE
虚拟点读笔下载模型，deploy报错，大佬能提供下yml吗

### ISSUE THREAD

**Issue by liaobiao** [enpeizhao/CVprojects#10]

**Comment by enpeizhao** [comment]
@liaobiao 对应paddle官网部署方式：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/python

另外注意我用的object detection模型时static模型，部署有所区别

**Comment by Alex28132** [comment]
> @liaobiao 对应paddle官网部署方式：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/python
> 
> 另外注意我用的object detection模型时static模型，部署有所区别

我在static文件夹下deploy也报错，能分享下yml就好了
