### ISSUE TITLE
没有创建方块

### ISSUE THREAD

**Issue by shishuyao** [enpeizhao/CVprojects#11]
Win10  py3.6
没有创建方块和手指线，只开启了摄像头？

**Comment by enpeizhao** [comment]
根据报错debug，应该是你mediapipe没有安装成功

**Comment by shishuyao** [comment]
奇怪，提示找不到这个方法
`mp.solutions.drawing_styles`
mp.solutions下面只有以下方法，的确没有找到drawing_styles
`import mediapipe.python.solutions.drawing_utils
import mediapipe.python.solutions.face_detection
import mediapipe.python.solutions.face_mesh
import mediapipe.python.solutions.hands
import mediapipe.python.solutions.holistic
import mediapipe.python.solutions.objectron
import mediapipe.python.solutions.pose
`

**Comment by enpeizhao** [comment]
mediapipe版本问题，换一个版本，或者自己重写这个方法

**Comment by shishuyao** [comment]
删除style对应的代码后可以正常运行了，感谢！
