### ISSUE TITLE
"yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'" 

### ISSUE THREAD

**Issue by zhubenfu** [enpeizhao/CVprojects#12]
I hava download "cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams",but I donot find fight yml file.
I use this methods "
python tools/export_model.py -c "models\cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml" --output_dir=./inference_model -o weights="models\cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams"
" but I got this issue 
"yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'"

**Comment by enpeizhao** [comment]
check this: https://github.com/PaddlePaddle/PaddleDetection/issues/2813

**Comment by zhubenfu** [comment]
Zhu Ben-FuCEOTel: +86 150-5813-3936weixin：portumoE-mail: ***@***.*** 前后相机同时拍 http://www.feelu.cn

**Comment by zhubenfu** [comment]
The program ran successfully。
python baidu_pp_wrap.py OK！
python demo.py：
but i  get a new problem:
两只手，开始画框的时候：程序崩溃了
  File "9.virtual reader\baidu_pp_detection\python\preprocess.py", line 136, in generate_scale
    im_scale = float(self.target_size) / float(im_size_min)
ZeroDivisionError: float division by zero

**Comment by enpeizhao** [comment]
这个要问飞桨，或者向上找一下原因

**Comment by zhubenfu** [comment]
Zhu Ben-FuCEOTel: +86 150-5813-3936weixin：portumoE-mail: ***@***.*** 前后相机同时拍 http://www.feelu.cn
