### ISSUE TITLE
请问这里在生成蒙版文件时，每一帧都显示 第x帧无数据 是为什么？

### ISSUE THREAD

**Issue by jkd2021** [enpeizhao/CVprojects#19]
请问这里在生成蒙版文件时，每一帧都显示 第x帧无数据 是为什么？：
https://github.com/enpeizhao/CVprojects/blob/main/codes/15.%E9%98%B2%E6%8C%A1%E5%BC%B9%E5%B9%95/README.md#22%E7%94%9F%E6%88%90%E8%92%99%E7%89%88%E6%96%87%E4%BB%B6

**Comment by enpeizhao** [comment]
提示来源于这里，说明实例未切割出来，根据pixellib官网检查一下
[                print("第{num}帧无数据".format(num=frame_index))](https://github.com/enpeizhao/CVprojects/blob/d1cf6d2f7ebd9eff4c412828964207c520ea92f0/codes/15.%E9%98%B2%E6%8C%A1%E5%BC%B9%E5%B9%95/demo.py#L97)

**Comment by jkd2021** [comment]
不好意思啊up主，还是没搞明白。我照着步骤一步步做的，但就是检测不出，debug的时候，发现是Mask RCNN的结果不对，每次运行demo.py，得到的class_ids还不一样，有toilet、clock之类稀奇古怪的，但就是没有person（明明视频里只有人啊喂）。请问up主知道这大概是怎么回事吗

**Comment by enpeizhao** [comment]
去pixellib文档看一下，或者换一个模型试试。

**Comment by leoyfj** [comment]
https://github.com/ayoolaolafenwa/PixelLib#pixellib-tensorflow-version

https://tensorflow.google.cn/install/source_windows?hl=cn#gpu

根据上面2个文档 ，和本项目的描述python==3.8 , 把tensorflow版本和python环境重新安装为合适的就可以了

**Comment by enpeizhao** [comment]
👍🏻👍🏻👍🏻
