### ISSUE TITLE
人员越界及聚众项目

### ISSUE THREAD

**Issue by Mr-Second** [enpeizhao/CVprojects#27]
你好，请问人员越界及聚众项目的校准数据集列表文件是github release中的哪个文件呀？看起来都不像呀，

![image](https://user-images.githubusercontent.com/38907693/227768620-f62e16ce-acd1-4f9c-9b0a-6e89c3e594e2.png)

另外能提供下人员越界及聚众的那段视频文件嘛，麻烦大佬了！

**Comment by enpeizhao** [comment]
量化校准集是自己做的图片就行。

**Comment by m178520** [comment]
大佬，权重文件怎么找不到啊，大佬可以提供一下吗

**Comment by enpeizhao** [comment]
reademe不是有吗，ONNX的，需要build 为engine

**Comment by m178520** [comment]
找到了，在下面藏着的，没看到，谢谢博主
