### ISSUE TITLE
人员越界与聚集项目中 cmakelists文件runtime.cu文件没找到

### ISSUE THREAD

**Issue by gitmhg** [enpeizhao/CVprojects#28]
![image](https://user-images.githubusercontent.com/51695758/229405412-ec24157c-7b21-449d-8a8e-3ada66a71c29.png)

**Comment by enpeizhao** [comment]
那是单线程的，直接注释掉吧，用runtime_thread.cu即可

**Comment by zongyu0210** [comment]
streamer.so是成功编译出来了，但是在下面引用他的时候却报错了，这怎么解决？谢谢！

/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avformat_network_init'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avformat_network_deinit'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_close'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_find_encoder'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avformat_write_header'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avio_open2'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_frame_free'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_log_set_level'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_open2'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_dict_set'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_interleaved_write_frame'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avformat_alloc_output_context2'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_image_get_buffer_size'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_send_frame'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_register_all'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `sws_freeContext'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_init_packet'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_dict_free'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_get_name'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_mallocz'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `sws_scale'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_parameters_from_context'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_dump_format'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avio_close'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avformat_new_stream'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_rescale_q'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_receive_packet'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_frame_alloc'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_image_fill_arrays'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_alloc_context3'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avcodec_free_context'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `sws_getContext'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `avformat_free_context'
/usr/bin/ld: streamer/libstreamer.so: undefined reference to `av_packet_unref'
