### ISSUE TITLE
关于onnx文件

### ISSUE THREAD

**Issue by xingmche** [enpeizhao/CVprojects#30]
您好，请问这个yolov5s_person.onnx是从哪里得到的啊？我直接从官方下了文件yolov5s.onnx似乎用不了QAQ

**Comment by yujingli1** [comment]
[你从他给的下载地址下载吧，这个作者大佬把模型的输出层改了，方便在源码中模型输出调用结果
![屏幕截图 2024-04-03 223553](https://github.com/enpeizhao/CVprojects/assets/144522390/6de97357-18b9-4613-8294-21cb259c330d)
他在源码中这样调用的模型输出结果：
![屏幕截图 2024-04-03 223722](https://github.com/enpeizhao/CVprojects/assets/144522390/654b9aa0-8b78-4fb0-b518-67c23eb06dbc)

**Comment by yujingli1** [comment]
作者大大，可能是出于简化和优化代码的想法吧，但是yolov5模型输出层访问起来速度是比较快的，不像yolov8那样修改了模型输出层之后对他的访问会拖慢程序运行时间，如果想用自己的下的官方的模型可以：
const float* prob = static_cast<const float*>(buffers.getHostBuffer(outputTensorName));
outputTensorName写自己模型输出层的名称，然后再自己写模型数据的解析，组成Detection类输入容器

**Comment by xingmche** [comment]
> 作者大大，可能是出于简化和优化代码的想法吧，但是yolov5模型输出层访问起来速度是比较快的，不像yolov8那样修改了模型输出层之后对他的访问会拖慢程序运行时间，如果想用自己的下的官方的模型可以： const float* prob = static_cast<const float*>(buffers.getHostBuffer(outputTensorName)); outputTensorName写自己模型输出层的名称，然后再自己写模型数据的解析，组成Detection类输入容器

多谢老哥解答！

**Comment by yujingli1** [comment]
私信了作者大大，作者大大说删除“原有的decode模块”

**Comment by yujingli1** [comment]
私信了作者大大怎么弄这样的输出层，他说删除原有的decode模块
